// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAjLzdLxY5cxNFN4DI3H-8RNUAieYoo3w',
    appId: '1:392537566029:web:53393c653f77ae517c6504',
    messagingSenderId: '392537566029',
    projectId: 'fleetcontrol-ecdc1',
    authDomain: 'fleetcontrol-ecdc1.firebaseapp.com',
    storageBucket: 'fleetcontrol-ecdc1.firebasestorage.app',
    measurementId: 'G-L6CKQWXLLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpz1c6OqLraDenM7EHZQwGQRhL_x_B38o',
    appId: '1:392537566029:android:2fc4043c3df50a697c6504',
    messagingSenderId: '392537566029',
    projectId: 'fleetcontrol-ecdc1',
    storageBucket: 'fleetcontrol-ecdc1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAjLzdLxY5cxNFN4DI3H-8RNUAieYoo3w',
    appId: '1:392537566029:web:1fd7b18e3c942cd67c6504',
    messagingSenderId: '392537566029',
    projectId: 'fleetcontrol-ecdc1',
    authDomain: 'fleetcontrol-ecdc1.firebaseapp.com',
    storageBucket: 'fleetcontrol-ecdc1.firebasestorage.app',
    measurementId: 'G-GQXRFY3C36',
  );
}
